### ISSUE TITLE
J1, pinout in schematic and PCB (Gerber file) does not match.

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/FETPulser#3]
In the schematic J1 pin 2 is connected to the pin number 1 of IC7, and pin 3 of the connector J1 is connected to pin 2 of IC7, while in PCB board file (which I sent for manufacturing) the labeling is not the same. 
I attach the pictures below.

**Schematic** 
![image](https://user-images.githubusercontent.com/23444211/114121704-6a38a600-9921-11eb-8a32-954959b19017.png)

**PCB board file**
![image](https://user-images.githubusercontent.com/23444211/114122728-7aea1b80-9923-11eb-9c82-ea04bfb3a52e.png)

**So this will also alter the polarity jumper positions?**

**Comment by bhclowers** [comment]
I think you misunderstand the schematic and the board files. While the schematic describes the linkages between parts, it does not dictate what the board looks like. They are two separate files.  The orientation of the jumpers is an option that was built in.  Keep it as positive and move from there.
